AWSTemplateFormatVersion: '2010-09-09'
Description: Authentication resources for JankenHockey (Cognito User Pool, Authentication Function)

Parameters:
  LambdaBucket:
    Type: String
    Description: S3 Bucket name where Lambda code is stored.
  LambdaZipFile:
    Type: String
    Description: S3 Key for the Lambda zip file.
  JankenHockeyFunctionRoleArn:
    Type: String
    Description: IAM Role ARN for Lambda functions.

Resources:
  ############################
  # Authentication
  ############################
  # Cognito User Pool
  JankenHockeyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      UserPoolName: JankenHockeyUserPool
      UserPoolTier: ESSENTIALS 
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: false
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
      AliasAttributes: []
      UsernameAttributes: []
      AutoVerifiedAttributes: []
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      UserPoolTags:
        Project: JankenHockey

  # Cognito User Pool Client
  JankenHockeyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      UserPoolId: !Ref JankenHockeyCognitoUserPool
      ClientName: JankenHockeyClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  # Lambda Authorizer Function
  JankenHockeyAuthorizerFunction:
    Type: AWS::Lambda::Function
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      FunctionName: JankenHockeyAuthorizerFunction
      Handler: auth.handler
      Role: !Ref JankenHockeyFunctionRoleArn
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaZipFile
      Runtime: python3.12
      Timeout: 30
      Environment:
        Variables:
          USER_POOL_ID: !Ref JankenHockeyCognitoUserPool
          CLIENT_ID: !Ref JankenHockeyCognitoUserPoolClient
      Tags:
        - Key: Project
          Value: JankenHockey

Outputs:
  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt JankenHockeyCognitoUserPool.Arn
    Export:
      Name: UserPoolArn

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref JankenHockeyCognitoUserPool
    Export:
      Name: UserPoolId

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref JankenHockeyCognitoUserPoolClient
    Export:
      Name: UserPoolClientId

  AuthorizerFunctionName:
    Description: Lambda Authorizer Function Name
    Value: !Ref JankenHockeyAuthorizerFunction
    Export:
      Name: AuthorizerFunctionName
