AWSTemplateFormatVersion: "2010-09-09"
Description: WebHosting for JankenHockey with Origin Access Control

Parameters:
  OperatorMailAddress:
    Type: String
    Description: mail address for operator.
  LambdaBucket:
    Type: String
    Description: S3 bucket name for Lambda function.
  LambdaZipFile:
    Type: String
    Description: Lambda function Zip name.

Resources:
  # RoomList Lambd Function IAM Role
  JankenHockeyRoomFunctionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      RoleName: JankenHockeyRoomFunctionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: JankenHockeyRoomFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !Sub arn:aws:dynamodb:ap-northeast-1:${AWS::AccountId}:table/Room

  # Game History Function IAM Role (for CPU battle history saving)
  JankenHockeyGameHistoryFunctionRole:
    Type: AWS::IAM::Role
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      RoleName: JankenHockeyGameHistoryFunctionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: JankenHockeyGameHistoryFunctionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !Sub arn:aws:dynamodb:ap-northeast-1:${AWS::AccountId}:table/GameHistory

  ############################
  # Authentication
  ############################
  AuthStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.${AWS::Region}.amazonaws.com/${Bucket}/authentication-stack.yaml"
        - Bucket: !Ref LambdaBucket
      Parameters:
        LambdaBucket: !Ref LambdaBucket
        LambdaZipFile: !Ref LambdaZipFile
        JankenHockeyFunctionRoleArn: !GetAtt JankenHockeyRoomFunctionRole.Arn
      Tags:
        - Key: Project
          Value: JankenHockey

  ############################
  # WebHosting
  ############################
  WebHostingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.${AWS::Region}.amazonaws.com/${Bucket}/web-hosting-stack.yaml"
        - Bucket: !Ref LambdaBucket
      Parameters:
        RestApiId: !GetAtt RestAPIStack.Outputs.JankenHockeyRestAPIId
      Tags:
        - Key: Project
          Value: JankenHockey

  ############################
  # WebSocket API
  ############################
  WebSocketAPIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.${AWS::Region}.amazonaws.com/${Bucket}/websocket-api-stack.yaml"
        - Bucket: !Ref LambdaBucket
      Parameters:
        LambdaBucket: !Ref LambdaBucket
        LambdaZipFile: !Ref LambdaZipFile
        UserPoolArn: !GetAtt AuthStack.Outputs.UserPoolArn
        UserPoolId: !GetAtt AuthStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt AuthStack.Outputs.UserPoolClientId
        CloudFrontOriginUrl: !GetAtt WebHostingStack.Outputs.JankenHockeyCloudFrontOriginUrl
      Tags:
        - Key: Project
          Value: JankenHockey

  ############################
  # Rest API
  ############################
  RestAPIStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.${AWS::Region}.amazonaws.com/${Bucket}/rest-api-stack.yaml"
        - Bucket: !Ref LambdaBucket
      Parameters:
        LambdaBucket: !Ref LambdaBucket
        LambdaZipFile: !Ref LambdaZipFile
        JankenHockeyFunctionRoleArn: !GetAtt JankenHockeyRoomFunctionRole.Arn
        JankenHockeyGameHistoryFunctionRoleArn: !GetAtt JankenHockeyGameHistoryFunctionRole.Arn
      Tags:
        - Key: Project
          Value: JankenHockey

  ############################
  # Monitoring
  ############################
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://s3.${AWS::Region}.amazonaws.com/${Bucket}/monitoring-stack.yaml"
        - Bucket: !Ref LambdaBucket
      Parameters:
        OperatorMailAddress: !Ref OperatorMailAddress
        ConnectFunctionName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyConnectFunctionName
        DefaultFunctionName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyDefaultFunctionName
        DisconnectFunctionName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyDisconnectFunctionName
        LoginFunctionName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyLoginFunctionName
        GameTimeoutFunctionName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyGameTimeoutFunctionName
        GetRoomsFunctionName: !GetAtt RestAPIStack.Outputs.JankenHockeyGetRoomsFunctionName
        CreateRoomFunctionName: !GetAtt RestAPIStack.Outputs.JankenHockeyCreateRoomFunctionName
        JoinRoomFunctionName: !GetAtt RestAPIStack.Outputs.JankenHockeyJoinRoomFunctionName
        SaveCpuBattleHistoryFunctionName: !GetAtt RestAPIStack.Outputs.JankenHockeySaveCpuBattleHistoryFunctionName
        SaveGuestCpuBattleHistoryFunctionName: !GetAtt RestAPIStack.Outputs.JankenHockeySaveGuestCpuBattleHistoryFunctionName
        AuthorizerFunctionName: !GetAtt AuthStack.Outputs.AuthorizerFunctionName
        GameHistoryTableName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyGameHistoryTableName
        ConnectionTableName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyConnectionTableName
        RoomTableName: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyRoomTableName
        WebSocketApiId: !GetAtt WebSocketAPIStack.Outputs.JankenHockeyWebSocketAPIId

      Tags:
        - Key: Project
          Value: JankenHockey

Outputs:
  WebHostingStackName:
    Description: The name of the WebHosting stack
    Value: !Ref WebHostingStack

  RestAPIStackName:
    Description: The name of the Rest API stack
    Value: !Ref RestAPIStack

  WebSocketAPIStackName:
    Description: The name of the WebSocket API stack
    Value: !Ref WebSocketAPIStack

  AuthStackName:
    Description: The name of the Authentication stack
    Value: !Ref AuthStack

  MonitoringStackName:
    Description: The name of the Monitoring stack
    Value: !Ref MonitoringStack
