AWSTemplateFormatVersion: '2010-09-09'
Description: WebHosting for JankenHockey with Origin Access Control

Parameters:
  LambdaBucket:
    Type: String
    Description: S3 bucket name for Lambda function Zip file.
  LambdaZipFile:
    Type: String
    Description: Lambda function Zip Package file name.

Resources:
  ############################
  # WebHosting
  ############################
  ## S3
  # S3バケット
  JankenHockeyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: janken-hockey-website-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: JankenHockey

  # S3バケットポリシー
  JankenHockeyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref JankenHockeyBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${JankenHockeyBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${JankenHockeyCloudFrontDistribution}'
  
  ## CloudFront
  # オリジンアクセスコントロール
  JankenHockeyOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: JankenHockeyOAC
        OriginAccessControlOriginType: s3
        SigningProtocol: sigv4
        SigningBehavior: always

  # CloudFrontディストリビューション
  JankenHockeyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt JankenHockeyBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref JankenHockeyOriginAccessControl
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        DefaultRootObject: index.html
      Tags:
        - Key: Project
          Value: JankenHockey

  ############################
  # API
  ############################
  ## DynamoDB
  # DynamoDB
  JankenHockeyGameHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: GameHistory
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: JankenHockey

  JankenHockeyConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Connection
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: JankenHockey

  ## Lambda
  # Lambda関数
  JankenHockeyConnectFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: JankenHockeyConnectFunction
      Handler: connect.handler
      Role: !GetAtt JankenHockeyFunctionRole.Arn
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaZipFile
      Runtime: python3.12
      Timeout: 30
      Tags:
        - Key: Project
          Value: JankenHockey

  # Lambda関数
  JankenHockeySendMessageFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: JankenHockeySendMessageFunction
      Handler: send_message.handler
      Role: !GetAtt JankenHockeyFunctionRole.Arn
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaZipFile
      Runtime: python3.12
      Timeout: 30
      Tags:
        - Key: Project
          Value: JankenHockey

  # Lambda関数
  JankenHockeyDisconnectFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: JankenHockeyDisconnectFunction
      Handler: disconnect.handler
      Role: !GetAtt JankenHockeyFunctionRole.Arn
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaZipFile
      Runtime: python3.12
      Timeout: 30
      Tags:
        - Key: Project
          Value: JankenHockey

  # Lambda関数ロール
  JankenHockeyFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: JankenHockeyFunctionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: JankenHockeyFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt JankenHockeyConnectionTable.Arn
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt JankenHockeyGameHistoryTable.Arn
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JankenHockeyAPI}/*/*/*
              - Effect: Allow
                Action:
                  - execute-api:ManageConnections
                Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JankenHockeyAPI}/*/*/*/*

  ## API Gateway
  # API Gateway IAMロール
  JankenHockeyAPIRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: JankenHockeyAPIRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: JankenHockeyAPIPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt JankenHockeyConnectFunction.Arn
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt JankenHockeySendMessageFunction.Arn
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt JankenHockeyDisconnectFunction.Arn

  # API
  JankenHockeyAPI:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: MyApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      ApiKeySelectionExpression: $request.header.x-api-key
  
  # API Gateway ロググループ
  MyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - '-'
        - - !Ref JankenHockeyAPI
          - access-logs

# Connect Route
  JankenHockeyAPIConnectRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref JankenHockeyAPI
      RouteKey: $connect
      Target: !Sub 'integrations/${JankenHockeyAPIConnectIntegration}'

  JankenHockeyAPIConnectIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref JankenHockeyAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JankenHockeyConnectFunction.Arn}/invocations'
      PayloadFormatVersion: 1.0

  # Disconnect Route
  JankenHockeyAPIDisconnectRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref JankenHockeyAPI
      RouteKey: $disconnect
      Target: !Sub 'integrations/${JankenHockeyAPIDisconnectIntegration}'

  JankenHockeyAPIDisconnectIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref JankenHockeyAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JankenHockeyDisconnectFunction.Arn}/invocations'
      PayloadFormatVersion: 1.0

  # sendMessage Route
  JankenHockeyAPISendMessageRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref JankenHockeyAPI
      RouteKey: sendMessage
      Target: !Sub 'integrations/${JankenHockeyAPISendMessageIntegration}'

  JankenHockeyAPISendMessageIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref JankenHockeyAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${JankenHockeySendMessageFunction.Arn}/invocations'
      PayloadFormatVersion: 1.0

  # Lambda Permissions
  JankenHockeyConnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt JankenHockeyConnectFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JankenHockeyAPI}/*/*/*

  JankenHockeyDisconnectPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt JankenHockeyDisconnectFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JankenHockeyAPI}/*/*/*

  JankenHockeySendMessagePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt JankenHockeySendMessageFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${JankenHockeyAPI}/*/*/*

  # API Gateway Deployment
  JankenHockeyAPIDeployment:
    Type: 'AWS::ApiGatewayV2::Deployment'
    Properties:
      ApiId: !Ref JankenHockeyAPI
    DependsOn:
      - JankenHockeyAPIConnectRoute
      - JankenHockeyAPIDisconnectRoute
      - JankenHockeyAPISendMessageRoute

  # API Gateway ステージおよびログ出力設定
  JankenHockeyAPIStage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref JankenHockeyAPI
      DeploymentId: !Ref JankenHockeyAPIDeployment
      StageName: prod
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
        LoggingLevel: INFO
        DataTraceEnabled: false
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 10
      AccessLogSettings:
        DestinationArn: !GetAtt MyLogGroup.Arn
        Format: >-
          {"requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller",
          "user":"$context.identity.user","requestTime":"$context.requestTime",
          "eventType":"$context.eventType","routeKey":"$context.routeKey",
          "status":"$context.status","connectionId":"$context.connectionId"}
