name: Backend Auto Deploy

on:
  push:
    branches:
      - main
env:
  AWS_REGION: 'ap-northeast-1'

jobs:
  deploy:
    name: Auto Deploy Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Lambda
        run: |
          cd infra
          ./package_lambda.sh
          ./deploy.sh
        env:
          STACK_NAME: janken-hockey
          LAMBDA_BUCKET: matchasong-lambda-bucket
          LAMBDA_ZIP_PREFIX: janken-hockey-lambda
